"""
Agentic RAG Market Research Analyst - Main Entry Point

This script provides a simple CLI interface to analyze companies and generate
investment memos using the complete agentic RAG pipeline.

Usage:
    python main.py                    # Interactive mode
    python main.py Tesla TSLA         # Direct analysis
    python main.py --visualize        # Show graph structure

Requirements:
    - GOOGLE_API_KEY environment variable
    - TAVILY_API_KEY environment variable

Examples:
    # Interactive mode with company selection
    python main.py

    # Analyze specific company
    python main.py "Apple Inc" AAPL

    # Visualize the graph
    python main.py --visualize

    # Save memo to custom file
    python main.py Tesla TSLA --output tesla_analysis.md
"""

import os
import sys
import argparse
from dotenv import load_dotenv
from graph import analyze_company, visualize_graph
import traceback

load_dotenv()

def check_environment():
    """Check if required environment variables are set"""
    google_key = os.getenv("GOOGLE_API_KEY")
    tavily_key = os.getenv("TAVILY_API_KEY")

    missing = []

    if not google_key:
        missing.append("GOOGLE_API_KEY")

    if not tavily_key:
        missing.append("TAVILY_API_KEY")

    if missing:
        print("Missing required API keys:")
        for key in missing:
            print(f"   • {key}")
        print("\nSet them with:")
        if "GOOGLE_API_KEY" in missing:
            print("  export GOOGLE_API_KEY='your-google-key'")
            print("  Get from: https://aistudio.google.com/apikey")
        if "TAVILY_API_KEY" in missing:
            print("  export TAVILY_API_KEY='your-tavily-key'")
            print("  Get from: https://tavily.com")
        return False

    return True

def interactive_mode():
    """Run in interactive mode, prompting for company info"""
    print("\n" + "=" * 80)
    print("Agentic RAG Market Research Analyst")
    print("=" * 80)
    print("\nThis tool will:")
    print("  1. Research the company using web search and financial databases")
    print("  2. Analyze market position, financials, and competitive landscape")
    print("  3. Generate a professional investment memo with recommendations")
    print("\nNote: Analysis takes 30-60 seconds and uses API credits")
    print("=" * 80 + "\n")

    # Get company info from user
    company = input("Enter company name (e.g., 'Tesla'): ").strip()
    if not company:
        print("Company name is required")
        return

    ticker = input("Enter stock ticker (e.g., 'TSLA'): ").strip().upper()
    if not ticker:
        print("Stock ticker is required")
        return

    output_file = input(f"Output file (default: memo_{ticker}.md): ").strip()
    if not output_file:
        output_file = f"memo_{ticker}.md"

    # Confirm
    print(f"\nAnalyzing: {company} ({ticker})")
    print(f"Output: {output_file}")

    proceed = input("\nProceed? (y/n): ").strip().lower()
    if proceed != 'y':
        print("Cancelled.")
        return

    # Run analysis
    run_analysis(company, ticker, output_file)

def run_analysis(company: str, ticker: str, output_file: str):
    """Run the analysis and save results"""
    print("\n" + "=" * 80)
    print("Starting Analysis...")
    print("=" * 80 + "\n")

    try:
        # Run the complete pipeline
        result = analyze_company(company, ticker, verbose=True)

        # Extract memo
        memo = result["memo_sections"]["full_draft"]

        # Save to file
        with open(output_file, "w") as f:
            f.write(f"# Investment Memo: {company} ({ticker})\n\n")
            f.write("*Generated by Agentic RAG Market Research Analyst*\n\n")
            f.write("---\n\n")
            f.write(memo)

        # Print summary
        print("\n" + "=" * 80)
        print("Analysis Complete!")
        print("=" * 80)

        print("\nStatistics:")
        print(f"   • Research Iterations: {result.get('research_iterations', 0)}")
        print(f"   • Financial Data Points: {len(result.get('financial_context', []))}")
        print(f"   • Market Data Points: {len(result.get('market_context', []))}")
        print(f"   • Memo Length: {len(memo)} characters (~{len(memo.split())} words)")

        print(f"\nOutput: {output_file}")

        # Show preview
        print("\n" + "=" * 80)
        print("Preview (first 1000 characters):")
        print("=" * 80)
        print(memo[:1000])
        if len(memo) > 1000:
            print("\n... [see full memo in file] ...")
        print("=" * 80 + "\n")

        print(f"Investment memo saved to: {output_file}\n")

    except Exception as e:
        print(f"\nAnalysis failed: {e}")
        traceback.print_exc()
        sys.exit(1)

def main():
    """Main entry point"""
    parser = argparse.ArgumentParser(
        description="Agentic RAG Market Research Analyst - Generate investment memos",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python main.py                      # Interactive mode
  python main.py Tesla TSLA           # Analyze Tesla
  python main.py "Apple Inc" AAPL     # Analyze Apple
  python main.py --visualize          # Show graph structure
  python main.py Tesla TSLA -o out.md # Custom output file

Environment Variables:
  GOOGLE_API_KEY    - Google AI API key (required)
  TAVILY_API_KEY    - Tavily Search API key (required)

Get API keys:
  Google: https://aistudio.google.com/apikey
  Tavily: https://tavily.com
        """
    )

    parser.add_argument(
        "company",
        nargs="?",
        help="Company name (e.g., 'Tesla')"
    )

    parser.add_argument(
        "ticker",
        nargs="?",
        help="Stock ticker (e.g., 'TSLA')"
    )

    parser.add_argument(
        "-o", "--output",
        help="Output file path (default: memo_<TICKER>.md)"
    )

    parser.add_argument(
        "--visualize",
        action="store_true",
        help="Visualize the graph structure and exit"
    )

    args = parser.parse_args()

    # Handle visualization
    if args.visualize:
        print("\nGenerating graph visualization...\n")
        visualize_graph()
        return

    # Check environment
    if not check_environment():
        sys.exit(1)

    # Interactive vs direct mode
    if args.company and args.ticker:
        # Direct mode
        output_file = args.output or f"memo_{args.ticker}.md"
        run_analysis(args.company, args.ticker, output_file)
    elif args.company or args.ticker:
        # Incomplete arguments
        print("Both company name and ticker are required")
        print("Usage: python main.py <company> <ticker>")
        print("   Or: python main.py (for interactive mode)")
        sys.exit(1)
    else:
        # Interactive mode
        interactive_mode()

if __name__ == "__main__":
    main()